### ISSUE TITLE
Example LLC4320 does not work anymore

### ISSUE THREAD

**Issue by dhruvbalwada** [pangeo-data/pangeo-ocean-examples#22]
The example in this notebook does not work anymore: 
https://github.com/pangeo-data/pangeo-ocean-examples/blob/master/llc4320.ipynb

This is probably a result of limited resources or something else. 
Trying to run it on ocean.pangeo just results in killed workers during the plotting step. 

While running it on binder results in the following error being displayed infinitely:
```
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /srv/conda/envs/notebook/lib/python3.7/asyncio/tasks.py:596> exception=AssertionError()>
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.7/asyncio/tasks.py", line 603, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/deploy/spec.py", line 51, in _
    assert self.status == "running"
AssertionError
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <zmq.eventloop.ioloop.ZMQIOLoop object at 0x7f371f5018d0>>, <Task finished coro=<SpecCluster._correct_state_internal() done, defined at /srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/deploy/spec.py:300> exception=AssertionError()>)
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/deploy/spec.py", line 335, in _correct_state_internal
    await w  # for tornado gen.coroutine support
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/deploy/spec.py", line 51, in _
    assert self.status == "running"
AssertionError
```

**Comment by rabernat** [comment]
This example was never really stable. It's too big.
